public class ActOnCleanUpScheduled  {
     public static void ve (String s) {
        
      
    }
 
   /* global void execute(SchedulableContext ctx) {
        List<Contact> contacts = [SELECT ID FROM 
                                  Contact 
                                  WHERE Act_OnRecordType__c !=NUll 
                                  OR C2__c !=NULL OR F2__c != NULL 
                                  OR Event_Referral_Source__c != NULL 
                                  LIMIT 200]; 
        
        List <Contact> newContacts = new List <Contact>();  
        for(contact ac: contacts) { 
            ac.C2__c = NULL;           
            ac.F2__c = NULL;
            ac.L2__c = NULL;
            ac.B2__c =NULL;
            ac.G2__c =NULL;
            ac.Acc2__c = false;
            ac.Y2__c = NULL;
            ac.P2__c= NULL;
            ac.F3__c = NULL;
            ac.L3__c = NULL;
            ac.B3__c =NULL;
            ac.G3__c =NULL;
            ac.Acc3__c = False;
            ac.Y3__c = NULL;
            ac.p3__c= NULL;
          
            ac.F4__c = NULL;
            ac.L4__c = NULL;
            ac.B4__c =NULL;
            ac.G4__c =NULL;
            ac.Acc4__c = false;
            ac.Y4__c = NULL;
            ac.p4__c= NULL;
            
            ac.F5__c = NULL;
            ac.L5__c = NULL;
            ac.B5__c =NULL;
            ac.G5__c =NULL;
            ac.Acc5__c = false;
            ac.Y5__c = NULL;
            ac.p5__c= NULL;
            ac.F6__c = NULL;
            ac.L6__c = NULL;
            ac.B6__c =NULL;
            ac.G6__c =NULL;
            ac.Acc6__c = false;
            ac.Y6__c = NULL;
            ac.p6__c= NULL;
            ac.F7__c = NULL;
            ac.L7__c = NULL;
            ac.B7__c =NULL;
            ac.G7__c =NULL;
            ac.Acc7__c = false;
            ac.Y7__c = NULL;
            ac.p7__c= NULL;
            ac.F8__c = NULL;
            ac.L8__c = NULL;
            ac.B8__c =NULL;
            ac.G8__c =NULL;
            ac.Acc8__c = false;
            ac.Y8__c = NULL;
            ac.p8__c= NULL;
            ac.F9__c = NULL;
            ac.L9__c = NULL;
            ac.B9__c =NULL;
            ac.G9__c =NULL;
            ac.Acc9__c = false;
            ac.Y9__c = NULL;
            ac.p9__c= NULL;
            ac.Act_OnRecordType__c =NUll;
            ac.SFIN_AttendeeType__c=NULL;
            ac.Morning_Workshop__c =NULL;
            // ac.IRC_NumberChildren__c=NULL;
            ac.EventInterpretation__c=NULL;
            ac.IRC_FoodChoice__c=NULL;
            ac.Afternoon_Workshop__c=NULL;
            ac.Childcare_Request__c=False;
            ac.Event_Referral_Source__c = NULL;
            newContacts.add(ac);
        }
        update newContacts;
}*/
        
}